model_id = "mlx-community/Qwen3-Coder-Next-6bit"
family = "qwen"
base_model = "Qwen3 Coder Next 80B"
n_layers = 48
hidden_size = 2048
supports_tensor = true
tasks = ["TextGeneration"]
quantization = "6bit"

[storage_size]
in_bytes = 68899327465
